import React, { useEffect, useMemo, useState } from "react";
import { Bell, RefreshCw, TrendingDown, Zap, ShieldAlert, Clock3, Database, Settings2, Activity, Info } from "lucide-react";

const demo={generated_at:"Demo data — run scanner workflow to refresh",market_status:"READY",scanner_a:[],scanner_b:[]};
function Score({value}){const v=Number(value||0);return <div className="qs-score"><div className="qs-score-track"><span style={{width:`${Math.min(Math.max(v,0),100)}%`}}/></div><b>{v.toFixed(1)}</b></div>}
function Prob({x}){if(x.probability==null)return <span className="no">UNAVAILABLE</span>;const p=(x.probability*100).toFixed(1);const ci=x.probability_ci?` (${(x.probability_ci[0]*100).toFixed(0)}–${(x.probability_ci[1]*100).toFixed(0)}%)`:"";return <span className="prob">{p}%<small>{ci}</small></span>}
function Quality({x}){return <span className={`pill quality-${String(x.data_quality||"UNKNOWN").toLowerCase()}`}>{x.data_quality||"UNKNOWN"}</span>}
export default function QuantScanner(){
 const [data,setData]=useState(demo),[tab,setTab]=useState("A"),[loading,setLoading]=useState(false),[alerts,setAlerts]=useState(true);
 const load=async()=>{setLoading(true);try{const r=await fetch(`${process.env.PUBLIC_URL||""}/scanner-data.json?${Date.now()}`);if(r.ok)setData(await r.json())}catch(e){}setLoading(false)};
 useEffect(()=>{load()},[]);
 const all=[...(data.scanner_a||[]),...(data.scanner_b||[])], high=useMemo(()=>all.filter(x=>Number(x.score)>=90).length,[data]),top=Math.max(...all.map(x=>Number(x.score)||0),0);
 return <div className="quant-scanner"><header className="qs-header"><div className="qs-brand"><div className="qs-mark">QS</div><div><strong>QUANT SCANNER</strong><span>OPPORTUNITY RESEARCH ENGINE</span></div></div><div className="qs-actions"><span className="qs-live"><i/> {data.market_status||"READY"}</span><button onClick={load}><RefreshCw size={15} className={loading?"spin":""}/> Refresh</button><button className={alerts?"active":""} onClick={()=>setAlerts(!alerts)}><Bell size={15}/> Alerts</button></div></header>
 <main className="qs-main"><section className="qs-hero"><div><div className="qs-eyebrow">SYSTEMATIC MARKET RESEARCH</div><h1>Find the <em>extreme.</em><br/>Measure the evidence.</h1><p>Scanner A searches leveraged-fund overextension and historical reversal states. Scanner B searches short-interest crowding with price/volume confirmation. Scores rank setups; probabilities and confidence are reported separately.</p></div><div className="qs-status-card"><div><span>ENGINE STATUS</span><b>ONLINE</b></div><div><span>CANDIDATES</span><b>{all.length}</b></div><div><span>HIGH SCORE</span><b>{high}</b></div></div></section>
 <section className="qs-metrics"><div><small>SCANNER A</small><strong>{(data.scanner_a||[]).length}</strong><span>leveraged reversal</span></div><div><small>SCANNER B</small><strong>{(data.scanner_b||[]).length}</strong><span>squeeze setups</span></div><div><small>TOP SCORE</small><strong>{top.toFixed(1)}</strong><span>ranking only</span></div><div><small>LAST RUN</small><strong>AUTO</strong><span>{data.generated_at}</span></div></section>
 <section className="qs-panel"><div className="qs-tabs"><button className={tab==="A"?"selected":""} onClick={()=>setTab("A")}><TrendingDown size={16}/> A / LEVERAGED REVERSAL</button><button className={tab==="B"?"selected":""} onClick={()=>setTab("B")}><Zap size={16}/> B / SHORT SQUEEZE</button></div><div className="qs-table-wrap">{tab==="A"?<table><thead><tr><th>RANK</th><th>SYMBOL</th><th>SCORE</th><th>5D DOWNSIDE</th><th>EVIDENCE</th><th>Z</th><th>52W DIST.</th><th>RV</th><th>OPTIONS</th></tr></thead><tbody>{(data.scanner_a||[]).map((x,i)=><tr key={x.ticker}><td className="rank">{String(i+1).padStart(2,"0")}</td><td><strong>{x.ticker}</strong><small>{x.industry||"LEVERAGED / INVERSE"}</small></td><td><Score value={x.score}/></td><td><Prob x={x}/></td><td><Quality x={x}/><small>{x.probability_sample||0} samples</small></td><td>{x.z_score?.toFixed(2)}σ</td><td>{x.high_distance?.toFixed(1)}%</td><td>{x.relative_volume?.toFixed(1)}×</td><td><span className={x.options==="PASS"?"yes":"no"}>{x.options||"—"}</span></td></tr>)}</tbody></table>:<table><thead><tr><th>RANK</th><th>SYMBOL</th><th>SCORE</th><th>SHORT FLOAT</th><th>DTC</th><th>SI Δ</th><th>REG SHO</th><th>REL. VOL.</th><th>PRICE Δ</th><th>OPTIONS</th></tr></thead><tbody>{(data.scanner_b||[]).map((x,i)=><tr key={x.ticker}><td className="rank">{String(i+1).padStart(2,"0")}</td><td><strong>{x.ticker}</strong><small>{x.industry||"SHORT-SQUEEZE SETUP"}</small></td><td><Score value={x.score}/></td><td className="prob">{x.short_float==null?"—":`${x.short_float.toFixed(1)}%`}</td><td>{x.days_to_cover==null?"—":x.days_to_cover.toFixed(1)}</td><td>{x.si_change_pct==null?"—":`${x.si_change_pct.toFixed(1)}%`}</td><td>{x.reg_sho_short_volume_ratio==null?"—":`${(x.reg_sho_short_volume_ratio*100).toFixed(1)}%`}</td><td>{x.rel_volume?.toFixed(1)}×</td><td className="positive">+{x.price_change?.toFixed(1)}%</td><td><span className={x.options==="PASS"?"yes":"no"}>{x.options||"—"}</span></td></tr>)}</tbody></table>}</div></section>
 <section className="qs-grid"><div className="qs-info"><div className="qs-info-title"><ShieldAlert size={17}/> HOW TO READ IT</div><p><b>Score ≠ probability.</b> Score ranks the current setup. A downside probability is only shown when there are enough comparable historical observations. Confidence intervals widen naturally when evidence is weak.</p><div className="qs-tags"><span>NO TECH</span><span>NO BIOTECH</span><span>FINALIST-FIRST</span><span>NO FAKE PROBABILITIES</span></div></div><div className="qs-info"><div className="qs-info-title"><Activity size={17}/> EVIDENCE PIPELINE</div><div className="pipeline"><span>PRICE</span><b>→</b><span>FINRA SI</span><b>→</b><span>REG SHO</span><b>→</b><span>OPTIONS</span><b>→</b><span>ALERT</span></div><p className="muted">FINRA short interest is periodic rather than tick-by-tick; Reg SHO is a separate daily short-sale activity measure. They are intentionally not conflated.</p></div></section>
 <section className="qs-info"><div className="qs-info-title"><Info size={17}/> RESEARCH GUARDRAILS</div><p>Historical results are conditional frequencies, not guarantees. The engine records sample size and data status, keeps options checks finalist-only, and is designed for research rather than automatic trading.</p></section>
 <footer><span><Clock3 size={13}/> {data.generated_at}</span><span><Settings2 size={13}/> Research mode · no auto-trading</span></footer></main></div>
}