import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Bell, RefreshCw, TrendingDown, Zap, ShieldAlert, Clock3, Settings2, Activity, Info } from "lucide-react";

const demo={generated_at:"Demo data — run scanner workflow to refresh",market_status:"NO DATA",scanner_a:[],scanner_b:[]};
function Score({value}){const v=Number(value||0);return <div className="qs-score"><div className="qs-score-track"><span style={{width:`${Math.min(Math.max(v,0),100)}%`}}/></div><b>{v.toFixed(1)}</b></div>}
function Prob({x}){const raw=x.downside_probability_5d;if(raw==null)return <span className="no">UNAVAILABLE</span>;const p=Number(raw);const ci=x.probability_ci95;const text=Array.isArray(ci)?` (${(ci[0]*100).toFixed(0)}–${(ci[1]*100).toFixed(0)}%)`:"";return <span className="prob">{p.toFixed(1)}%<small>{text}</small></span>}
function Quality({x}){const q=x.evidence_quality||"UNKNOWN";return <span className={`pill quality-${String(q).toLowerCase()}`}>{q}</span>}
function OptionsStatus({x}){const status=x?.options?.status||"NOT_CHECKED";return <span className={status==="PASS"?"yes":"no"}>{status}</span>}
export default function QuantScanner(){
 const [data,setData]=useState(demo),[tab,setTab]=useState("A"),[loading,setLoading]=useState(false),[alerts,setAlerts]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(`${process.env.PUBLIC_URL||""}/scanner-data.json?${Date.now()}`);if(r.ok)setData(await r.json())}catch(e){}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const all=useMemo(()=>[...(data.scanner_a||[]),...(data.scanner_b||[])],[data.scanner_a,data.scanner_b]);
 const high=useMemo(()=>all.filter(x=>Number(x.score)>=90).length,[all]);
 const top=useMemo(()=>Math.max(...all.map(x=>Number(x.score)||0),0),[all]);
 return <div className="quant-scanner"><header className="qs-header"><div className="qs-brand"><div className="qs-mark">QS</div><div><strong>QUANT SCANNER</strong><span>OPPORTUNITY RESEARCH ENGINE</span></div></div><div className="qs-actions"><span className="qs-live"><i/> {data.market_status||"NO DATA"}</span><button onClick={load}><RefreshCw size={15} className={loading?"spin":""}/> Refresh</button><button className={alerts?"active":""} onClick={()=>setAlerts(!alerts)}><Bell size={15}/> Alerts</button></div></header>
 <main className="qs-main"><section className="qs-hero"><div><div className="qs-eyebrow">SYSTEMATIC MARKET RESEARCH</div><h1>Find the <em>extreme.</em><br/>Measure the evidence.</h1><p>Scanner A searches leveraged-fund overextension and historical reversal states. Scanner B searches short-interest crowding with price/volume confirmation. Scores rank setups; probabilities and confidence are reported separately.</p></div><div className="qs-status-card"><div><span>ENGINE STATUS</span><b>ONLINE</b></div><div><span>CANDIDATES</span><b>{all.length}</b></div><div><span>HIGH SCORE</span><b>{high}</b></div></div></section>
 <section className="qs-metrics"><div><small>SCANNER A</small><strong>{(data.scanner_a||[]).length}</strong><span>leveraged reversal</span></div><div><small>SCANNER B</small><strong>{(data.scanner_b||[]).length}</strong><span>squeeze setups</span></div><div><small>TOP SCORE</small><strong>{top.toFixed(1)}</strong><span>ranking only</span></div><div><small>LAST RUN</small><strong>AUTO</strong><span>{data.generated_at}</span></div></section>
 <section className="qs-panel"><div className="qs-tabs"><button className={tab==="A"?"selected":""} onClick={()=>setTab("A")}><TrendingDown size={16}/> A / LEVERAGED REVERSAL</button><button className={tab==="B"?"selected":""} onClick={()=>setTab("B")}><Zap size={16}/> B / SHORT SQUEEZE</button></div><div className="qs-table-wrap">{tab==="A"?<table><thead><tr><th>RANK</th><th>SYMBOL</th><th>SCORE</th><th>5D DOWNSIDE</th><th>EVIDENCE</th><th>Z20</th><th>52W DIST.</th><th>RV</th><th>OPTIONS</th></tr></thead><tbody>{(data.scanner_a||[]).map((x,i)=><tr key={x.ticker}><td className="rank">{String(i+1).padStart(2,"0")}</td><td><strong>{x.ticker}</strong><small>{x.industry||"LEVERAGED / INVERSE"}</small></td><td><Score value={x.score}/></td><td><Prob x={x}/></td><td><Quality x={x}/><small>{x.probability_sample||0} samples</small></td><td>{x.z20==null?"—":`${Number(x.z20).toFixed(2)}σ`}</td><td>{x.distance_52w==null?"—":`${Number(x.distance_52w).toFixed(1)}%`}</td><td>{x.relative_volume==null?"—":`${Number(x.relative_volume).toFixed(1)}×`}</td><td><OptionsStatus x={x}/></td></tr>)}</tbody></table>:<table><thead><tr><th>RANK</th><th>SYMBOL</th><th>SCORE</th><th>SHORT FLOAT</th><th>DTC</th><th>SI Δ</th><th>REG SHO</th><th>REL. VOL.</th><th>5D Δ</th><th>OPTIONS</th></tr></thead><tbody>{(data.scanner_b||[]).map((x,i)=><tr key={x.ticker}><td className="rank">{String(i+1).padStart(2,"0")}</td><td><strong>{x.ticker}</strong><small>{x.industry||"SHORT-SQUEEZE SETUP"}</small></td><td><Score value={x.score}/></td><td className="prob">{x.short_float_pct==null?"—":`${Number(x.short_float_pct).toFixed(1)}%`}</td><td>{x.days_to_cover==null?"—":Number(x.days_to_cover).toFixed(1)}</td><td>{x.si_change_pct==null?"—":`${Number(x.si_change_pct).toFixed(1)}%`}</td><td>{x.reg_sho_short_volume_ratio==null?"—":`${(Number(x.reg_sho_short_volume_ratio)*100).toFixed(1)}%`}</td><td>{x.relative_volume==null?"—":`${Number(x.relative_volume).toFixed(1)}×`}</td><td className="positive">{x.momentum_5d==null?"—":`${Number(x.momentum_5d)>=0?"+":""}${Number(x.momentum_5d).toFixed(1)}%`}</td><td><OptionsStatus x={x}/></td></tr>)}</tbody></table>}</div></section>
 <section className="qs-grid"><div className="qs-info"><div className="qs-info-title"><ShieldAlert size={17}/> HOW TO READ IT</div><p><b>Score ≠ probability.</b> Score ranks the current setup. A downside probability is only shown when there are enough comparable historical observations. Confidence intervals widen naturally when evidence is weak.</p><div className="qs-tags"><span>NO TECH</span><span>NO BIOTECH</span><span>FINALIST-FIRST</span><span>NO FAKE PROBABILITIES</span></div></div><div className="qs-info"><div className="qs-info-title"><Activity size={17}/> EVIDENCE PIPELINE</div><div className="pipeline"><span>PRICE</span><b>→</b><span>FINRA SI</span><b>→</b><span>REG SHO</span><b>→</b><span>OPTIONS</span><b>→</b><span>ALERT</span></div><p className="muted">FINRA short interest is periodic rather than tick-by-tick; Reg SHO is a separate daily short-sale activity measure. They are intentionally not conflated.</p></div></section>
 <section className="qs-info"><div className="qs-info-title"><Info size={17}/> RESEARCH GUARDRAILS</div><p>Historical results are conditional frequencies, not guarantees. The research ledger records one completed-daily observation per scanner/ticker/date, keeps live monitoring separate, and treats options gamma as model-derived context rather than dealer positioning.</p></section>
 <footer><span><Clock3 size={13}/> {data.generated_at}</span><span><Settings2 size={13}/> Research mode · no auto-trading</span></footer></main></div>
}